name: DevSecOps for DVPWA

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt || true # bo requirements może nie być kompletny

      - name: Dependency scan (SCA)
        run: |
          pip install pip-audit
          pip-audit || true

      - name: SAST scan with Semgrep
        run: |
          pip install semgrep
          semgrep --config p/default . || true

      - name: Run GitLeaks via Docker
        run: |
            docker run --rm -v $(pwd):/path zricethezav/gitleaks:latest detect --source=/path --no-git -v


      - name: Build Docker image
        run: docker build -t dvpwa:latest .

      - name: DAST scan with OWASP ZAP
        run: |
        mkdir zap-results
        docker run --network="host" -v $(pwd)/zap-results:/zap/wrk ghcr.io/zaproxy/zaproxy:stable zap-baseline.py \
        -t http://localhost:8080 \
        -r zap-report.html

      - name: Upload ZAP report
        uses: actions/upload-artifact@v4
        with:
          name: zap-report
          path: zap-report.html

      - name: Container image scan with Trivy
        uses: aquasecurity/trivy-action@master
        with:
          image-ref: dvpwa:latest
          format: table
          severity: HIGH,CRITICAL
